name: Lint

on: [push]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Install Node.js and NPM
              uses: actions/setup-node@v3
              id: node
              with:
                  node-version: 18
                  cache: npm
            - name: Configure blockware registry
              run: echo '@blockware:registry=${{ secrets.GCP_ARTIFACT_NPM_URL }}' >> .npmrc

            - name: npm install
              run: |
                  npm ci

            - name: Lint
              run: |
                  npm run lint
