name: Publish artifacts
on:
    release:
        types:
            - created

jobs:
    publish_mac:
        runs-on: macos-latest
        steps:
            - name: Checkout git repo
              uses: actions/checkout@v3

            - name: Install Node and NPM
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: npm

            - name: Install and build
              run: |
                  npm install
                  npm run postinstall
                  npm run build

            - name: Publish releases
              env:
                  # These values are used for auto updates signing
                  APPLE_ID: ${{ secrets.APPLE_ID }}
                  APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
                  APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
                  CSC_LINK: ${{ secrets.APPLE_CERTIFICATE_BASE64 }}
                  CSC_KEY_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
                  # This is used for uploading release assets to github
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  npm exec electron-builder -- --publish always --mac
