name: Release to stable
on:
  workflow_dispatch:

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          ref: master

      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branches: |
            ['master']
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
